// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojWcsggTlIP537jOocjNWUypWTSxJ90A',
    appId: '1:450323426117:web:859d58c701d85a1d97ec2c',
    messagingSenderId: '450323426117',
    projectId: 'flutter-prep-8e005',
    authDomain: 'flutter-prep-8e005.firebaseapp.com',
    databaseURL: 'https://flutter-prep-8e005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-8e005.firebasestorage.app',
    measurementId: 'G-2DH0VXHJ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSN4XBxCi8VNoLkZCYKIOr-jLjJqgCWY',
    appId: '1:450323426117:android:714eb6621132e36e97ec2c',
    messagingSenderId: '450323426117',
    projectId: 'flutter-prep-8e005',
    databaseURL: 'https://flutter-prep-8e005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-8e005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2c4CI8YDmeFbJdnhNDcDpeuOVXe7czI',
    appId: '1:450323426117:ios:a3e22413400a706397ec2c',
    messagingSenderId: '450323426117',
    projectId: 'flutter-prep-8e005',
    databaseURL: 'https://flutter-prep-8e005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-8e005.firebasestorage.app',
    iosBundleId: 'com.example.toanvuthinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd2c4CI8YDmeFbJdnhNDcDpeuOVXe7czI',
    appId: '1:450323426117:ios:a3e22413400a706397ec2c',
    messagingSenderId: '450323426117',
    projectId: 'flutter-prep-8e005',
    databaseURL: 'https://flutter-prep-8e005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-8e005.firebasestorage.app',
    iosBundleId: 'com.example.toanvuthinh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojWcsggTlIP537jOocjNWUypWTSxJ90A',
    appId: '1:450323426117:web:693f018314e8ba6d97ec2c',
    messagingSenderId: '450323426117',
    projectId: 'flutter-prep-8e005',
    authDomain: 'flutter-prep-8e005.firebaseapp.com',
    databaseURL: 'https://flutter-prep-8e005-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-8e005.firebasestorage.app',
    measurementId: 'G-WDHB5ZVESY',
  );

}